#!/usr/bin/env bash
# Manage my process script

ACTION=$1

case "$ACTION" in
    start)
        ./manage_my_process &
        echo $! > /tmp/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f /tmp/my_process.pid ]; then
            kill "$(cat /tmp/my_process.pid)"
            rm /tmp/my_process.pid
        fi
        echo "manage_my_process stopped"
        ;;
    restart)
        # Stop part
        if [ -f /tmp/my_process.pid ]; then
            kill "$(cat /tmp/my_process.pid)"
            rm /tmp/my_process.pid
        fi
        # Start part
        ./manage_my_process &
        echo $! > /tmp/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
